auto_update:
  cooldown_days: 7
  freeze: true
default_install_hook_types:
  - commit-msg
  - pre-commit
repos:
  - repo: builtin
    hooks:
      - id: check-added-large-files
        args: [ --enforce-all ]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-json5
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      # - id: file-contents-sorter
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [ --fix=no ]
      - id: no-commit-to-branch
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
      # - id: double-quote-string-fixer
      - id: forbid-submodules
      - id: name-tests-test
        args: [ --pytest-test-first ]
      # - id: sort-simple-yaml
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 8ff2449591c8de025b17661ba76d60237a1ae62b  # frozen: 0.12.1
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 39d9ac5938dadb73df0564a45f163e25ff9fa6e2  # frozen: v0.16.1
    hooks:
      - id: ruff-format
      - id: ruff-check
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 41e691678310dfd3833f7ab4e180ddb014310356  # frozen: v2.3.0
    hooks:
      - id: mypy
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 93c7b51d860138c34a0613756c0151209b88d56f  # frozen: v4.17.0
    hooks:
      - id: commitizen
  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # frozen: v1.38.0
    hooks:
      - id: yamllint
        args: [ --config-data, relaxed ]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 6b63472e72e1a91ed8a2f6d483790dfb644fa1d3  # frozen: 0.37.4
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-readthedocs
      - id: check-jsonschema
        alias: check-github-workflows-require-timeout
        name: Check GitHub Actions workflow jobs set timeout-minutes
        args:
          - --builtin-schema
          - github-workflows-require-timeout
        files: ^\.github/workflows/[^/]+$
        types:
          - yaml
