name: Test

run-name: ${{ github.actor }} is testing peprock 🚀

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        python-version:
          - >-
            3.10
          - 3.11
          - 3.12
          - 3.13
          - 3.14
          - 3.15
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      UV_FROZEN: 1
    timeout-minutes: 5

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${GITHUB_REF} and your repository is ${{ github.repository }}."
        env:
          GITHUB_REF: ${{ github.ref }}
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check code formatting
        run: uv run ruff format --check
      - name: Run linter
        run: uv run ruff check
      - name: Run type checker
        run: uv run mypy
      - name: Run unit tests
        run: uv run pytest --cov --cov-report=xml --junitxml=junit.xml -o junit_family=legacy
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        with:
          env_vars: OS,PYTHON
          files: ./coverage.xml
      - run: echo "🍏 This job's status is ${JOB_STATUS}."
        env:
          JOB_STATUS: ${{ job.status }}

  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          version: 'v1.28.0' # TODO: unpin after release >v1.29.0
